### ISSUE TITLE
Build breaks on armv7: error[E0407]: method `backtrace` is not a member of trait `Error`

### ISSUE THREAD

**Issue by yurivict** [eyre-rs/eyre#211]
Error:
```
[eyre 0.6.8] error[E0407]: method `backtrace` is not a member of trait `Error`
[eyre 0.6.8]   --> /wrkdirs/usr/ports/devel/cargo-spellcheck/work/target/release/build/eyre-75082b40f71007b4/out/probe.rs:19:9
[eyre 0.6.8]    |
[eyre 0.6.8] 19 | /         fn backtrace(&self) -> Option<&Backtrace> {
[eyre 0.6.8] 20 | |             let backtrace = Backtrace::capture();
[eyre 0.6.8] 21 | |             match backtrace.status() {
[eyre 0.6.8] 22 | |                 BacktraceStatus::Captured | BacktraceStatus::Disabled | _ => {}
[eyre 0.6.8] 23 | |             }
[eyre 0.6.8] 24 | |             unimplemented!()
[eyre 0.6.8] 25 | |         }
[eyre 0.6.8]    | |_________^ not a member of trait `Error`
[eyre 0.6.8] 
[eyre 0.6.8] error[E0554]: `#![feature]` may not be used on the stable release channel
[eyre 0.6.8]  --> /wrkdirs/usr/ports/devel/cargo-spellcheck/work/target/release/build/eyre-75082b40f71007b4/out/probe.rs:2:5
[eyre 0.6.8]   |
[eyre 0.6.8] 2 |     #![feature(backtrace)]
[eyre 0.6.8]   |     ^^^^^^^^^^^^^^^^^^^^^^
[eyre 0.6.8] 
[eyre 0.6.8] warning: the feature `backtrace` has been stable since 1.65.0 and no longer requires an attribute to enable
[eyre 0.6.8]  --> /wrkdirs/usr/ports/devel/cargo-spellcheck/work/target/release/build/eyre-75082b40f71007b4/out/probe.rs:2:16
[eyre 0.6.8]   |
[eyre 0.6.8] 2 |     #![feature(backtrace)]
[eyre 0.6.8]   |                ^^^^^^^^^
[eyre 0.6.8]   |
[eyre 0.6.8]   = note: `#[warn(stable_features)]` on by default
[eyre 0.6.8] 
```

The error was encountered during build of cargo-spellcheck-0.14.0

FreeBSD 14.1

**Comment by LeoniePhiline** [comment]
Will be fixed by https://github.com/eyre-rs/eyre/commit/f80de3e49e65de3bcefec8efec041a524cab8022. Hopefully we can get an `eyre` v0.6.13 out while working on v1.0.0. See https://github.com/eyre-rs/eyre/pull/269#issuecomment-4210587359 / https://github.com/eyre-rs/eyre/issues/266#issuecomment-4210579759.
