### ISSUE TITLE
doctests fail to compile with thiserror 1.0.40

### ISSUE THREAD

**Issue by decathorpe** [eyre-rs/eyre#94]
Running `cargo test` works up until `thiserror 1.0.39`, but starts to fail with `thiserror 1.0.40` - these two doctests fail to compile:

```
test src/macros.rs - macros::ensure (line 85) ... FAILED
test src/macros.rs - macros::bail (line 25) ... FAILED
```

This can be reproduced by running:

```
cargo update
cargo test
```

Running these two commands makes tests pass again:

```
cargo update --package thiserror --precise 1.0.39
cargo test
```

The test suite of  `anyhow`  failed with similar errors in some recent versions, but the most recent version(s) apparently fixed this problem. It might be necessary to backport some `anyhow` changes into `eyre`. It seems to be related to the update to `syn ^2`.

Complete error message:

```
---- src/macros.rs - macros::ensure (line 85) stdout ----
error: unexpected token
  --> src/macros.rs:98:2
   |
15 | }, 1).1,
   |  ^

error[E0599]: the method `eyre_kind` exists for reference `&ScienceError`, but its trait bounds were not satisfied
   --> src/macros.rs:104:1
    |
9   | enum ScienceError {
    | -----------------
    | |
    | doesn't satisfy `ScienceError: Into<ErrReport>`
    | doesn't satisfy `ScienceError: eyre::kind::TraitKind`
    | doesn't satisfy `ScienceError: std::fmt::Display`
...
21  | ensure!(depth <= MAX_DEPTH, ScienceError::RecursionLimitExceeded);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `&ScienceError` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `ScienceError: Into<ErrReport>`
            which is required by `ScienceError: eyre::kind::TraitKind`
            `ScienceError: std::fmt::Display`
            which is required by `&ScienceError: eyre::kind::AdhocKind`
            `&ScienceError: Into<ErrReport>`
            which is required by `&ScienceError: eyre::kind::TraitKind`
note: the traits `Into` and `std::fmt::Display` must be implemented
   --> /home/deca/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:786:1
    |
786 | pub trait Display {
    | ^^^^^^^^^^^^^^^^^
    |
   ::: /home/deca/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:447:1
    |
447 | pub trait Into<T>: Sized {
    | ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the macro `$crate::eyre` which comes from the expansion of the macro `ensure` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
Couldn't compile the test.
---- src/macros.rs - macros::bail (line 25) stdout ----
error: unexpected token
  --> src/macros.rs:38:2
   |
15 | }, 1).1,
   |  ^

error[E0277]: the trait bound `ScienceError: std::error::Error` is not satisfied
  --> src/macros.rs:43:47
   |
20 |     let err: &'static dyn std::error::Error = &ScienceError::RecursionLimitExceeded;
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `ScienceError`
   |
   = note: required for the cast from `ScienceError` to the object type `dyn std::error::Error`

error[E0599]: the method `eyre_kind` exists for reference `&ScienceError`, but its trait bounds were not satisfied
   --> src/macros.rs:46:5
    |
9   | enum ScienceError {
    | -----------------
    | |
    | doesn't satisfy `ScienceError: Into<ErrReport>`
    | doesn't satisfy `ScienceError: eyre::kind::TraitKind`
    | doesn't satisfy `ScienceError: std::fmt::Display`
...
23  |     bail!(ScienceError::RecursionLimitExceeded);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `&ScienceError` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `ScienceError: Into<ErrReport>`
            which is required by `ScienceError: eyre::kind::TraitKind`
            `ScienceError: std::fmt::Display`
            which is required by `&ScienceError: eyre::kind::AdhocKind`
            `&ScienceError: Into<ErrReport>`
            which is required by `&ScienceError: eyre::kind::TraitKind`
note: the traits `Into` and `std::fmt::Display` must be implemented
   --> /home/deca/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:786:1
    |
786 | pub trait Display {
    | ^^^^^^^^^^^^^^^^^
    |
   ::: /home/deca/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:447:1
    |
447 | pub trait Into<T>: Sized {
    | ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the macro `$crate::eyre` which comes from the expansion of the macro `bail` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
Couldn't compile the test.
```
